In [1]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm

In [2]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [3]:
# from local system

df_lnc_die = pd.read_csv(r"./lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [4]:

df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [5]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [6]:
dataset1

lncRNA             miRNA         Disease  PubMed ID
0    NONHSAT000612.2    hsa-miR-570-3p  Osteoarthritis   34780784
1    NONHSAT000612.2    hsa-miR-651-3p  Osteoarthritis   34780784
2    NONHSAT000612.2   hsa-miR-449b-3p  Osteoarthritis   34780784
3    NONHSAT000612.2   hsa-miR-1468-3p  Osteoarthritis   34780784
4    NONHSAT000612.2    hsa-miR-874-5p  Osteoarthritis   34780784
..               ...               ...             ...        ...
590  NONHSAT015292.2      hsa-miR-9902  Osteoarthritis   34780784
591  NONHSAT015292.2  hsa-miR-10522-5p  Osteoarthritis   34780784
592  NONHSAT015292.2  hsa-miR-10526-3p  Osteoarthritis   34780784
593  NONHSAT015292.2   hsa-miR-9851-3p  Osteoarthritis   34780784
594  NONHSAT015292.2     hsa-miR-12118  Osteoarthritis   34780784

[595 rows x 4 columns]

In [7]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [8]:
df = dataset2.copy()
df

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [ ]:
df = dataset2.copy()

In [42]:
# only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [45]:
disease = [a[:-1] for a in open("./disease.txt").readlines()]
lncRNA = [a[:-1] for a in open("./lncRNA.txt").readlines()]
miRNA = [a[:-1] for a in open("./miRNA.txt").readlines()]

In [10]:
# len(df['lncRNA'].unique()),len(df['miRNA'].unique()),len(df['Disease'].unique()),

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [11]:
LM_Graph = nx.Graph()
MD_Graph = nx.Graph()
LD_Graph = nx.Graph()

LM_Graph.add_nodes_from(lncRNA)
LM_Graph.add_nodes_from(miRNA)

LD_Graph.add_nodes_from(lncRNA)
LD_Graph.add_nodes_from(disease)

MD_Graph.add_nodes_from(miRNA)
MD_Graph.add_nodes_from(disease)

In [12]:
for a in df.values:
    LM_Graph.add_edge(a[0],a[1])
    MD_Graph.add_edge(a[1],a[2])
    LD_Graph.add_edge(a[0],a[2])

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [13]:
LM_index = {a:b for (a,b) in zip(LM_Graph.nodes(),range(len(LM_Graph.nodes())))}
MD_index = {a:b for (a,b) in zip(MD_Graph.nodes(),range(len(MD_Graph.nodes())))}
LD_index = {a:b for (a,b) in zip(LD_Graph.nodes(),range(len(LD_Graph.nodes())))}

In [14]:
LM_M_A = nx.adjacency_matrix(LM_Graph).todense()
MD_M_A = nx.adjacency_matrix(MD_Graph).todense()
LD_M_A = nx.adjacency_matrix(LD_Graph).todense()

In [15]:
LM_M = np.zeros(shape=(len(lncRNA),len(miRNA)))
MD_M = np.zeros(shape=(len(miRNA), len(disease)))
LD_M = np.zeros(shape=(len(lncRNA), len(disease)))

In [16]:
for a in range(len(lncRNA)):
    for b in range(len(miRNA)):
        LM_M[a][b] = LM_M_A[LM_index[lncRNA[a]]][LM_index[miRNA[b]]]
LM_M

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
for a in range(len(miRNA)):
    for b in range(len(disease)):
        MD_M[a][b] = MD_M_A[MD_index[miRNA[a]]][MD_index[disease[b]]]
MD_M

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
LD = LM_M.dot(MD_M)
LD

array([[5., 6., 6., ..., 0., 0., 0.],
       [3., 5., 5., ..., 0., 0., 0.],
       [7., 9., 7., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
CD = np.zeros(shape=(len(disease),len(disease)))
for i in range(len(disease)):
    for j in range(len(disease)):
        CD[i][j] = (LD[:,i].dot(LD[:,j]))/(norm(LD[:,i])*norm(LD[:,j]))
CD 

array([[1.        , 0.97285384, 0.93395138, ..., 0.34518445, 0.34518445,
        0.30128703],
       [0.97285384, 1.        , 0.97980751, ..., 0.40133147, 0.40133147,
        0.29389721],
       [0.93395138, 0.97980751, 1.        , ..., 0.34004333, 0.34004333,
        0.28647844],
       ...,
       [0.34518445, 0.40133147, 0.34004333, ..., 1.        , 1.        ,
        0.18249022],
       [0.34518445, 0.40133147, 0.34004333, ..., 1.        , 1.        ,
        0.18249022],
       [0.30128703, 0.29389721, 0.28647844, ..., 0.18249022, 0.18249022,
        1.        ]])

In [22]:
CL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
for i in range(len(lncRNA)):
    for j in range(len(lncRNA)):
        CL[i][j] = (LD[i,:].dot(LD[j,:]))/(norm(LD[i,:])*norm(LD[j,:]))


array([[1.        , 0.9899882 , 0.92600943, ..., 0.6296417 , 0.83640136,
        0.56538621],
       [0.9899882 , 1.        , 0.95507861, ..., 0.59793085, 0.80259174,
        0.53944955],
       [0.92600943, 0.95507861, 1.        , ..., 0.50798934, 0.66022589,
        0.406601  ],
       ...,
       [0.6296417 , 0.59793085, 0.50798934, ..., 1.        , 0.55555556,
        0.35007002],
       [0.83640136, 0.80259174, 0.66022589, ..., 0.55555556, 1.        ,
        0.60678804],
       [0.56538621, 0.53944955, 0.406601  , ..., 0.35007002, 0.60678804,
        1.        ]])

In [32]:
CL_df = pd.DataFrame(CL)
CL_df.to_csv("./CL.csv")

Unnamed: 0  NONHSAT000002.2  NONHSAT000004.2  NONHSAT000008.2   
0     NONHSAT000002.2         1.000000         0.989988         0.926009  \
1     NONHSAT000004.2         0.989988         1.000000         0.955079   
2     NONHSAT000008.2         0.926009         0.955079         1.000000   
3     NONHSAT000009.2         0.941081         0.965939         0.995728   
4     NONHSAT000010.2         0.947516         0.970677         0.987005   
...               ...              ...              ...              ...   
7549  NONHSAT000708.2         0.482446         0.444841         0.321969   
7550  NONHSAT017054.2         0.629642         0.597931         0.507989   
7551  NONHSAT017055.2         0.629642         0.597931         0.507989   
7552  NONHSAT013732.2         0.836401         0.802592         0.660226   
7553  NONHSAT007829.2         0.565386         0.539450         0.406601   

      NONHSAT000009.2  NONHSAT000010.2  NONHSAT000013.2  NONHSAT000014.2   
0            0.941081         0.947516         0.982625         0.958676  \
1            0.965939         0.970677         0.988803         0.975663   
2            0.995728         0.987005         0.975043         0.984225   
3            1.000000         0.992916         0.982925         0.989210   
4            0.992916         1.000000         0.982122         0.983403   
...               ...              ...              ...              ...   
7549         0.329967         0.328652         0.399620         0.336209   
7550         0.519563         0.527076         0.581711         0.539762   
7551         0.519563         0.527076         0.581711         0.539762   
7552         0.685054         0.693397         0.769070         0.738981   
7553         0.421970         0.422167         0.482549         0.430602   

      NONHSAT000016.2  NONHSAT000024.2  ...  NONHSAT005620.2  NONHSAT008624.2   
0            0.977545         0.996781  ...         0.482446         0.482446  \
1            0.981850         0.982848  ...         0.444841         0.444841   
2            0.961280         0.911561  ...         0.321969         0.321969   
3            0.971699         0.930912  ...         0.329967         0.329967   
4            0.970318         0.937457  ...         0.328652         0.328652   
...               ...              ...  ...              ...              ...   
7549         0.410423         0.484200  ...         1.000000         1.000000   
7550         0.578546         0.657654  ...         0.288675         0.288675   
7551         0.578546         0.657654  ...         0.288675         0.288675   
7552         0.753957         0.839330  ...         0.577350         0.577350   
7553         0.533908         0.561833  ...         0.727607         0.727607   

      NONHSAT002404.2  NONHSAT015532.2  NONHSAT014001.2  NONHSAT000708.2   
0            0.734611         0.692840         0.683559         0.482446  \
1            0.700017         0.652775         0.632783         0.444841   
2            0.600744         0.511728         0.498578         0.321969   
3            0.629651         0.533996         0.530670         0.329967   
4            0.643408         0.541131         0.544140         0.328652   
...               ...              ...              ...              ...   
7549         0.208514         0.577350         0.408248         1.000000   
7550         0.481543         0.555556         0.589256         0.288675   
7551         0.481543         0.555556         0.589256         0.288675   
7552         0.762444         0.666667         0.549972         0.577350   
7553         0.252861         0.793492         0.495074         0.727607   

      NONHSAT017054.2  NONHSAT017055.2  NONHSAT013732.2  NONHSAT007829.2  
0            0.629642         0.629642         0.836401         0.565386  
1            0.597931         0.597931         0.802592         0.539450  
2            0.507989         0.507989         0.660226         0.406601  

In [25]:
CL = pd.read_csv("./CL.csv")

In [29]:
CL


TypeError: 'RangeIndex' object is not callable