In [1]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm


In [2]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [3]:
# from local system
df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [4]:
df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [5]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [6]:
dataset1

lncRNA             miRNA         Disease  PubMed ID
0    NONHSAT000612.2    hsa-miR-570-3p  Osteoarthritis   34780784
1    NONHSAT000612.2    hsa-miR-651-3p  Osteoarthritis   34780784
2    NONHSAT000612.2   hsa-miR-449b-3p  Osteoarthritis   34780784
3    NONHSAT000612.2   hsa-miR-1468-3p  Osteoarthritis   34780784
4    NONHSAT000612.2    hsa-miR-874-5p  Osteoarthritis   34780784
..               ...               ...             ...        ...
590  NONHSAT015292.2      hsa-miR-9902  Osteoarthritis   34780784
591  NONHSAT015292.2  hsa-miR-10522-5p  Osteoarthritis   34780784
592  NONHSAT015292.2  hsa-miR-10526-3p  Osteoarthritis   34780784
593  NONHSAT015292.2   hsa-miR-9851-3p  Osteoarthritis   34780784
594  NONHSAT015292.2     hsa-miR-12118  Osteoarthritis   34780784

[595 rows x 4 columns]

In [7]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [8]:
df = dataset2.copy()
df

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [9]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [10]:
lncRNA = np.array([a[:-1] for a in open("./lncRNA.txt").readlines()])
miRNA = np.array([a[:-1] for a in open("./miRNA.txt").readlines()])
disease = np.array([a[:-1] for a in open("./disease.txt").readlines()])

In [11]:
len(lncRNA),len(miRNA),len(disease)

(7554, 239, 514)

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [12]:
G = nx.Graph()
for a in df:
    for b in df[a].unique().tolist():
        G.add_node(b)
for a in df.values:
    G.add_edge(a[1],a[2])
    G.add_edge(a[0],a[1])
    G.add_edge(a[2],a[0])

In [13]:
mergedAdjencymatrix = nx.adjacency_matrix(G).todense()
index_node = {a:b for (a,b) in zip(G.nodes(),range(len(G.nodes())))}

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [ ]:
LD = np.zeros(shape=(len(lncRNA),len(disease)))
LD_row_index = {a:i for i,a in enumerate(lncRNA)}
LD_col_index = {a:i for i,a in enumerate(disease)}
for a,i in LD_row_index.items():
    for b,j in LD_col_index.items():
        LD[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
LD

In [14]:
LMD = np.zeros(shape=(len(lncRNA),len(miRNA)+len(disease)))
LMD_row_index = {a:i for i,a in enumerate(lncRNA)}
LMD_col_index = {a:i for i,a in enumerate(miRNA.tolist()+disease.tolist())}
for a,i in LMD_row_index.items():
    for b,j in LMD_col_index.items():
        LMD[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
LMD

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
DML = np.zeros(shape=(len(disease), len(lncRNA)+len(miRNA)))
DML_row_index = {a:i for i,a in enumerate(disease)}
DML_col_index = {a:i for i,a in enumerate(miRNA.tolist()+lncRNA.tolist())}
for a,i in DML_row_index.items():
    for b,j in DML_col_index.items():
        DML[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
DML

array([[1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
lam = 0.2

In [17]:
# # only run this if the SL.csv not found
# SL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
# for i in range(len(lncRNA)):
#     for j in range(len(lncRNA)):
#         SL[i][j] = (lam*norm(LMD[i].dot(LMD[j])) + (1-lam)*norm(LMD[i]-LMD[j]))/np.sqrt(len(LMD[0]))
# np.savetxt("./SL.csv",SL,delimiter=',',fmt="%.5f")

In [18]:
SL = np.loadtxt("./SL.csv",delimiter=',',dtype=float)

In [19]:
# # # run this only if SD.csv not found
# SD = np.zeros(shape=(len(disease),len(disease)))
# for i in range(len(disease)):
#     for j in range(len(disease)):
#         SD[i][j] = (lam*norm(DML[i]*DML[j]) + (1-lam)*norm(DML[i]-DML[j]))/np.sqrt(len(DML[0]))
# np.savetxt("./SD.csv",SD,delimiter=",",fmt="%.5f")

In [20]:
SD = np.loadtxt("./SD.csv",delimiter=',',dtype=float)

In [21]:
#Run this if Y1 is not found (this runs for 26 to 46 mins)
#For each element in the association matrix LMD that is zero, the function fills it in by considering the values of the nearest neighbors in the similarity matrix  SL
#Like this, we have to perform for DML w.r.t SD too
k = 217   #Assumed in the paper
a = np.zeros((len(LMD), len(LMD[0])))
for i in range(len(LMD)):
    for j in range(len(LMD[0])):
        a[i, j] = LMD[i, j]
K = np.zeros((len(LMD), k))
for i in range(len(SL)):
    for j in range(k):
        K[i, j] = int(SL[i].argsort()[-j - 1])  #sorting in descending order and selecting the first k indices (because only k is required. Ipdi panna dhan largest value front la vandhurum and we can take most similar near value.
for i in range(len(LMD)):
        for j in range(len(LMD[0])):
            if LMD[i, j] == 0:
                for t in range(len(K[0])):
                    n = int(K[i, t])
                    alpha = (k - t) * 2 / (k * (k + 1))                 #Omega formula in paper (pg5 ending)
                    a[i, j] = a[i, j] + LMD[n, j] * SL[i, n] * alpha    #Formulae in paper (pg6 starting)
np.savetxt("Y1.csv",a,delimiter=',',fmt="%.5f") # saving this matrix to a file
a       #a must be the updated LMD matrix

array([[1.        , 1.        , 1.        , ..., 1.96537337, 1.96537337,
        1.77204786],
       [1.        , 1.        , 1.        , ..., 1.80896274, 1.80896274,
        1.67765462],
       [1.        , 4.40763393, 1.        , ..., 1.83531596, 1.83531596,
        1.72980853],
       ...,
       [0.8697787 , 0.84489233, 0.8697787 , ..., 0.39827743, 0.39827743,
        0.34130477],
       [0.92473562, 0.90591801, 0.92473562, ..., 0.41542857, 0.41542857,
        0.35154652],
       [0.81738349, 0.80076748, 0.81738349, ..., 0.35698359, 0.35698359,
        0.31184877]])

In [28]:
Y1 = np.loadtxt("Y1.csv",delimiter=',',dtype=float)

In [22]:
#Didn't run the below code even once

In [38]:
k = 217   
b = np.zeros((len(DML), len(DML[0])))
for i in range(len(DML)):
    for j in range(len(DML[0])):
        b[i, j] = DML[i, j]
K = np.zeros(shape=(len(DML), k))
for i in range(len(SD)):
    for j in range(k):
        K[i, j] = int(SD[i].argsort()[-j - 1])  
for i in range(len(DML)):
        for j in range(len(DML[0])):
            if DML[i, j] == 0:
                for t in range(len(K[0])):
                    n = int(K[i, t])
                    alpha = (k - t) * 2 / (k * (k + 1))               
                    b[i, j] = a[i, j] + DML[n, j] * SD[i, n] * alpha    
b       #b must be the updated DML matrix

IndexError: index 2606 is out of bounds for axis 1 with size 753