In [2]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm


In [2]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [3]:
# from local system
df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [4]:
df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [5]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [6]:
dataset1

lncRNA             miRNA         Disease  PubMed ID
0    NONHSAT000612.2    hsa-miR-570-3p  Osteoarthritis   34780784
1    NONHSAT000612.2    hsa-miR-651-3p  Osteoarthritis   34780784
2    NONHSAT000612.2   hsa-miR-449b-3p  Osteoarthritis   34780784
3    NONHSAT000612.2   hsa-miR-1468-3p  Osteoarthritis   34780784
4    NONHSAT000612.2    hsa-miR-874-5p  Osteoarthritis   34780784
..               ...               ...             ...        ...
590  NONHSAT015292.2      hsa-miR-9902  Osteoarthritis   34780784
591  NONHSAT015292.2  hsa-miR-10522-5p  Osteoarthritis   34780784
592  NONHSAT015292.2  hsa-miR-10526-3p  Osteoarthritis   34780784
593  NONHSAT015292.2   hsa-miR-9851-3p  Osteoarthritis   34780784
594  NONHSAT015292.2     hsa-miR-12118  Osteoarthritis   34780784

[595 rows x 4 columns]

In [7]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [8]:
df = dataset2.copy()
df

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [9]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [4]:
lncRNA = np.array([a[:-1] for a in open("./lncRNA.txt").readlines()])
miRNA = np.array([a[:-1] for a in open("./miRNA.txt").readlines()])
disease = np.array([a[:-1] for a in open("./disease.txt").readlines()])

In [11]:
len(lncRNA),len(miRNA),len(disease)

(7554, 239, 514)

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [12]:
G = nx.Graph()
for a in df:
    for b in df[a].unique().tolist():
        G.add_node(b)
for a in df.values:
    G.add_edge(a[1],a[2])
    G.add_edge(a[0],a[1])
    G.add_edge(a[2],a[0])

In [13]:
mergedAdjencymatrix = nx.adjacency_matrix(G).todense()
index_node = {a:b for (a,b) in zip(G.nodes(),range(len(G.nodes())))}

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [14]:
LD = np.zeros(shape=(len(lncRNA),len(disease)))
LD_row_index = {a:i for i,a in enumerate(lncRNA)}
LD_col_index = {a:i for i,a in enumerate(disease)}
for a,i in LD_row_index.items():
    for b,j in LD_col_index.items():
        LD[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
LD

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
LMD = np.zeros(shape=(len(lncRNA),len(miRNA)+len(disease)))
LMD_row_index = {a:i for i,a in enumerate(lncRNA)}
LMD_col_index = {a:i for i,a in enumerate(miRNA.tolist()+disease.tolist())}
for a,i in LMD_row_index.items():
    for b,j in LMD_col_index.items():
        LMD[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
LMD

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
DML = np.zeros(shape=(len(disease), len(lncRNA)+len(miRNA)))
DML_row_index = {a:i for i,a in enumerate(disease)}
DML_col_index = {a:i for i,a in enumerate(miRNA.tolist()+lncRNA.tolist())}
for a,i in DML_row_index.items():
    for b,j in DML_col_index.items():
        DML[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
DML

array([[1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
lam = 0.2

In [18]:
# # only run this if the SL.csv not found
# SL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
# for i in range(len(lncRNA)):
#     for j in range(len(lncRNA)):
#         SL[i][j] = (lam*norm(LMD[i].dot(LMD[j])) + (1-lam)*norm(LMD[i]-LMD[j]))/np.sqrt(len(LMD[0]))
# np.save("SL",SL)

In [19]:
SL = np.load("./SL.npy")

In [20]:
# # # run this only if SD.csv not found
# SD = np.zeros(shape=(len(disease),len(disease)))
# for i in range(len(disease)):
#     for j in range(len(disease)):
#         SD[i][j] = (lam*norm(DML[i]*DML[j]) + (1-lam)*norm(DML[i]-DML[j]))/np.sqrt(len(DML[0]))
# np.save("SD",SD)

In [21]:
SD = np.load('SD.npy')

In [22]:
k = 217 

In [23]:
wt_ = (2)/(k*(k+1)) 

In [24]:
#  #If u dont have y1, run this , this runs for around 7 mins  (this ran with k = 217)
# Y1 = LD.copy()
# KL = np.zeros(shape=(len(lncRNA),k))
# for i in range(len(lncRNA)):
#     sl_ = SL[i].argsort()[::-1]
#     for j in range(k):
#         KL[i][j] = sl_[j]
# for i in range(len(lncRNA)):
#     for j in range(len(disease)):
#         if Y1[i][j] == 0:
#             for t in range(k): 
#                 # wt = 2*(k-t)/(k*(k+1)) this is computaional expens
#                 wt = wt_*(k-t)
#                 n = int(KL[i][t])
#                 Y1[i][j] += LD[n][j]*SL[i][n]*wt
# np.save("Y1",Y1)

In [25]:
Y1 = np.load("Y1.npy")

In [28]:
# # run this only if Y2 in not there this run for around 8 mins(this ran with k = 217)
#  Y2 = LD.copy()
# Y2 = Y2.T
# KD = np.zeros(shape=(len(disease),k))
# Y_t = LD.T
# for i in range(len(disease)):
#     sd_ = SD[i].argsort()[::-1]
#     for j in range(k):
#         KD[i][j] = sd_[j]
# for i in range(Y2.shape[0]):
#     for j in range(Y2.shape[1]):
#         if Y2[i][j] == 0:
#             for t in range(k):
#                 wt = wt_*(k-t)
#                 n = int(KD[i][t])
#                 Y2[i][j] += Y_t[n][j]*SD[i][n]*wt 
# Y2 = Y2.T
# np.save("Y2",Y2)

In [29]:
Y2 = np.load("Y2.npy")

In [58]:
Y1.max()

5.142199168393014

In [59]:
Y2.max()

1.0

In [ ]:
# optimal values 
# nu1,nu2 = 0.12670215, 0.53003007431
# (0.999999999999591, 0.04042105250750801)
# nu1,nu2 = 0.12670215, 0.5300300743106127
# (1.0, 0.040421052507512635)

In [184]:
nu1,nu2 = 0.12670215, 0.5300300743106127
Y0 = np.zeros(shape=Y1.shape)
for i in range(Y0.shape[0]):
    for j in range(Y0.shape[1]):
        Y0[i][j] = nu1*Y1[i][j] + nu2*Y2[i][j]
# Y0/
Y0.max(),Y0.min()

(1.0, 0.040421052507512635)

In [ ]:
# np.save("Y0",Y0)

In [3]:
Y0 = np.load("Y0.npy")

In [7]:
d_len = len(disease)
l_len = len(lncRNA)
l = np.array([[a]*d_len for a in lncRNA]).flatten()
d = np.array(l_len*disease.tolist())
d.size,l.size

(3882756, 3882756)

In [8]:
stat_d = pd.DataFrame()
stat_d['lncRNA'] = l.copy()
stat_d['diease'] = d.copy()
stat_d['Algorithmic Value'] = Y0.flatten().copy()
stat_d['Algorithmic Value'] = stat_d['Algorithmic Value']

In [9]:
stat_d.to_csv("DMWNN_final_ouput.csv")

In [5]:
Y0.flatten().tolist().count(0)

0