In [2]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm


In [3]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [4]:
# from local system
df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [5]:
df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [6]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [7]:
dataset1

lncRNA             miRNA         Disease  PubMed ID
0    NONHSAT000612.2    hsa-miR-570-3p  Osteoarthritis   34780784
1    NONHSAT000612.2    hsa-miR-651-3p  Osteoarthritis   34780784
2    NONHSAT000612.2   hsa-miR-449b-3p  Osteoarthritis   34780784
3    NONHSAT000612.2   hsa-miR-1468-3p  Osteoarthritis   34780784
4    NONHSAT000612.2    hsa-miR-874-5p  Osteoarthritis   34780784
..               ...               ...             ...        ...
590  NONHSAT015292.2      hsa-miR-9902  Osteoarthritis   34780784
591  NONHSAT015292.2  hsa-miR-10522-5p  Osteoarthritis   34780784
592  NONHSAT015292.2  hsa-miR-10526-3p  Osteoarthritis   34780784
593  NONHSAT015292.2   hsa-miR-9851-3p  Osteoarthritis   34780784
594  NONHSAT015292.2     hsa-miR-12118  Osteoarthritis   34780784

[595 rows x 4 columns]

In [8]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017231.2    hsa-miR-4514                              Cancer
9376653  NONHSAT017231.2    hsa-miR-4514                   Vascular diseases
9376654  NONHSAT017231.2    hsa-miR-4533                              Cancer
9376655  NONHSAT017231.2    hsa-miR-4692                              Cancer
9376656  NONHSAT017231.2    hsa-miR-4692                   Vascular diseases

[9376657 rows x 3 columns]

In [9]:
df = dataset2.copy()
df

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017231.2    hsa-miR-4514                              Cancer
9376653  NONHSAT017231.2    hsa-miR-4514                   Vascular diseases
9376654  NONHSAT017231.2    hsa-miR-4533                              Cancer
9376655  NONHSAT017231.2    hsa-miR-4692                              Cancer
9376656  NONHSAT017231.2    hsa-miR-4692                   Vascular diseases

[9376657 rows x 3 columns]

In [10]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [11]:
lncRNA = np.array([a[:-1] for a in open("./lncRNA.txt").readlines()])
miRNA = np.array([a[:-1] for a in open("./miRNA.txt").readlines()])
disease = np.array([a[:-1] for a in open("./disease.txt").readlines()])

In [12]:
len(lncRNA),len(miRNA),len(disease)

(7554, 239, 514)

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [13]:
G = nx.Graph()
for a in df:
    for b in df[a].unique().tolist():
        G.add_node(b)
for a in df.values:
    G.add_edge(a[1],a[2])
    G.add_edge(a[0],a[1])
    G.add_edge(a[2],a[0])

In [14]:
mergedAdjencymatrix = nx.adjacency_matrix(G).todense()
index_node = {a:b for (a,b) in zip(G.nodes(),range(len(G.nodes())))}

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [15]:
LMD = np.zeros(shape=(len(lncRNA),len(miRNA)+len(disease)))
LMD_row_index = {a:i for i,a in enumerate(lncRNA)}
LMD_col_index = {a:i for i,a in enumerate(miRNA.tolist()+disease.tolist())}
for a,i in LMD_row_index.items():
    for b,j in LMD_col_index.items():
        LMD[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
LMD

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
DML = np.zeros(shape=(len(disease), len(lncRNA)+len(miRNA)))
DML_row_index = {a:i for i,a in enumerate(disease)}
DML_col_index = {a:i for i,a in enumerate(miRNA.tolist()+lncRNA.tolist())}
for a,i in DML_row_index.items():
    for b,j in DML_col_index.items():
        DML[i][j] = mergedAdjencymatrix[index_node[a]][index_node[b]]
DML

array([[1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
lam = 0.2

In [21]:
# only run this if the SL.csv not found
SL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
for i in range(len(lncRNA)):
    for j in range(len(lncRNA)):
        SL[i][j] = (lam*norm(LMD[i].dot(LMD[j])) + (1-lam)*norm(LMD[i]-LMD[j]))/np.sqrt(len(LMD[0]))
np.savetxt("./SL.csv",SL,delimiter=',',fmt="%.5f")

In [19]:
# SL = np.loadtxt("./SL.csv",delimiter=',',dtype=float)

FileNotFoundError: ./SL.csv not found.

In [22]:
# # run this only if SD.csv not found
SD = np.zeros(shape=(len(disease),len(disease)))
for i in range(len(disease)):
    for j in range(len(disease)):
        SD[i][j] = (lam*norm(DML[i]*DML[j]) + (1-lam)*norm(DML[i]-DML[j]))/np.sqrt(len(DML[0]))
np.savetxt("./SD.csv",SD,delimiter=",",fmt="%.5f")

In [ ]:
# SD = np.loadtxt("./SD.csv",delimiter=',',dtype=float)

In [24]:
#For each element in the association matrix LMD that is zero, the function fills it in by considering the values of the nearest neighbors in the similarity matrix  SL
#Like this, we have to perform for DML w.r.t SD too
k = 217   #Assumed in the paper
a = np.zeros((len(LMD), len(LMD[0])))
for i in range(len(LMD)):
    for j in range(len(LMD[0])):
        a[i, j] = LMD[i, j]
K = np.zeros((len(LMD), k))
for i in range(len(SL)):
    for j in range(k):
        K[i, j] = int(SL[i].argsort()[-j - 1])  #sorting in descending order and selecting the first k indices (because only k is required. Ipdi panna dhan largest value front la vandhurum and we can take most similar near value.
for i in range(len(LMD)):
        for j in range(len(LMD[0])):
            if LMD[i, j] == 0:
                for t in range(len(K[0])):
                    n = int(K[i, t])
                    alpha = (k - t) * 2 / (k * (k + 1))                 #Omega formula in paper (pg5 ending)
                    a[i, j] = a[i, j] + LMD[n, j] * SL[i, n] * alpha    #Formulae in paper (pg6 starting)
a       #a must be the updated LMD matrix

array([[1.        , 1.        , 1.        , ..., 1.96537339, 1.96537339,
        1.77204773],
       [1.        , 1.        , 1.        , ..., 1.8093378 , 1.8093378 ,
        1.67765501],
       [1.        , 4.40763352, 1.        , ..., 1.83531589, 1.83531589,
        1.72980845],
       ...,
       [0.86977875, 0.84492859, 0.86977875, ..., 0.39827729, 0.39827729,
        0.34126884],
       [0.92473511, 0.90591753, 0.92473511, ..., 0.41542834, 0.41542834,
        0.35154627],
       [0.81738325, 0.80076727, 0.81738325, ..., 0.35705053, 0.35705053,
        0.3118824 ]])

In [ ]:
#Weighted KNN updation of DM-L
k = 217   
b = np.zeros((len(DML), len(DML[0])))
for i in range(len(DML)):
    for j in range(len(DML[0])):
        b[i, j] = DML[i, j]
K = np.zeros((len(DML), k))
for i in range(len(SD)):
    for j in range(k):
        K[i, j] = int(SD[i].argsort()[-j - 1])  
for i in range(len(DML)):
        for j in range(len(DML[0])):
            if DML[i, j] == 0:
                for t in range(len(K[0])):
                    n = int(K[i, t])
                    alpha = (k - t) * 2 / (k * (k + 1))               
                    b[i, j] = a[i, j] + DML[n, j] * SD[i, n] * alpha    
b       #b must be the DML matrix