In [1]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm

In [2]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [3]:
# from local system

df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [4]:

df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [5]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [6]:
# dataset1

In [7]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [8]:
df = dataset2.copy()
# df

In [9]:
df = dataset2.copy()

In [10]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [11]:
disease = [a[:-1] for a in open("./disease.txt").readlines()]
lncRNA = [a[:-1] for a in open("./lncRNA.txt").readlines()]
miRNA = [a[:-1] for a in open("./miRNA.txt").readlines()]

In [12]:
len(lncRNA),len(miRNA),len(disease)

(7554, 239, 514)

In [13]:
lncRNA_index = {a:b for (a,b) in zip(lncRNA,range(len(lncRNA)))}
disease_index = {a:b for (a,b) in zip(disease,range(len(disease)))}
miRNA_index = {a:b for (a,b) in zip(miRNA,range(len(miRNA)))}

In [14]:
# len(df['lncRNA'].unique()),len(df['miRNA'].unique()),len(df['Disease'].unique()),

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [15]:
LM_Graph = nx.Graph()
MD_Graph = nx.Graph()
LD_Graph = nx.Graph()

LM_Graph.add_nodes_from(lncRNA)
LM_Graph.add_nodes_from(miRNA)

LD_Graph.add_nodes_from(lncRNA)
LD_Graph.add_nodes_from(disease)

MD_Graph.add_nodes_from(miRNA)
MD_Graph.add_nodes_from(disease)

In [16]:
for a in df.values:
    LM_Graph.add_edge(a[0],a[1])
    MD_Graph.add_edge(a[1],a[2])
    LD_Graph.add_edge(a[0],a[2])

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [17]:
LM_index = {a:b for (a,b) in zip(LM_Graph.nodes(),range(len(LM_Graph.nodes())))}
MD_index = {a:b for (a,b) in zip(MD_Graph.nodes(),range(len(MD_Graph.nodes())))}
LD_index = {a:b for (a,b) in zip(LD_Graph.nodes(),range(len(LD_Graph.nodes())))}

In [18]:
LM_M_A = nx.adjacency_matrix(LM_Graph).todense()
MD_M_A = nx.adjacency_matrix(MD_Graph).todense()
LD_M_A = nx.adjacency_matrix(LD_Graph).todense()

In [19]:
LM_M = np.zeros(shape=(len(lncRNA),len(miRNA)),dtype=int)
MD_M = np.zeros(shape=(len(miRNA), len(disease)),dtype=int)
LD_M = np.zeros(shape=(len(lncRNA), len(disease)),dtype=int)

In [20]:
for a in range(len(lncRNA)):
    for b in range(len(disease)):
        LD_M[a][b] = LD_M_A[LD_index[lncRNA[a]]][LD_index[disease[b]]]
LD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
for a in range(len(lncRNA)):
    for b in range(len(miRNA)):
        LM_M[a][b] = LM_M_A[LM_index[lncRNA[a]]][LM_index[miRNA[b]]]
LM_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
for a in range(len(miRNA)):
    for b in range(len(disease)):
        MD_M[a][b] = MD_M_A[MD_index[miRNA[a]]][MD_index[disease[b]]]
MD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
LD = LM_M.dot(MD_M)
LD

array([[5, 6, 6, ..., 0, 0, 0],
       [3, 5, 5, ..., 0, 0, 0],
       [7, 9, 7, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
# # run this if CD.csv is not found in the current folder(runs for seconds)
# CD = np.zeros(shape=(len(disease),len(disease)))
# for i in range(len(disease)):
#     for j in range(len(disease)):
#         CD[i][j] = (MD_M[:,i].dot(MD_M[:,j]))/(norm(MD_M[:,i])*norm(MD_M[:,j]))
# np.save("CD",CD)

In [25]:
CD = np.load("CD.npy")

In [26]:
# # run this if CL.csv not found in the current folder(run for 8 min )
# CL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
# for i in range(len(lncRNA)):
#     for j in range(len(lncRNA)):
#         CL[i][j] = (LM_M[i,:].dot(LM_M[j,:]))/(norm(LM_M[i,:])*norm(LM_M[j,:]))
# np.save("CL",CL)

In [27]:
CL = np.load("CL.npy")

In [28]:
JD = np.zeros(shape=CD.shape)
for i in range(MD_M.shape[-1]):
    for j in range(MD_M.shape[-1]):
        JD[i][j] =(np.bitwise_and(MD_M[:,i],MD_M[:,j]).sum())/(np.bitwise_or(MD_M[:,i],MD_M[:,j]).sum())
        

In [29]:
JL = np.zeros(shape=CL.shape)
for i in range(LM_M.shape[-1]):
    for j in range(LM_M.shape[-1]):
        JL[i][j] =(np.bitwise_and(LM_M[:,i],LM_M[:,j]).sum())/(np.bitwise_or(LM_M[:,i],LM_M[:,j]).sum())
JL      

array([[1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.28849315, 1.        , 0.28849315, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
IDS = np.zeros(shape=CD.shape)
for i in range(IDS.shape[0]):
    for j in range(IDS.shape[-1]):
        if CD[i][j] == 0:
            IDS[i][j] = JD[i][j]
        else:
            IDS[i][j] = (CD[i][j]+JD[i][j])/2
IDS

array([[1.        , 0.73534833, 0.62628227, ..., 0.        , 0.        ,
        0.        ],
       [0.73534833, 1.        , 0.79003636, ..., 0.19620955, 0.19620955,
        0.        ],
       [0.62628227, 0.79003636, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.19620955, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.19620955, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [31]:
ILS = np.zeros(shape=CL.shape)
for i in range(ILS.shape[0]):
    for j in range(ILS.shape[-1]):
        if CL[i][j] == 0:
            ILS[i][j] = JL[i][j]
        else:
            ILS[i][j] = (CL[i][j]+JL[i][j])/2
ILS

array([[1.        , 0.50909658, 0.80073   , ..., 0.        , 0.        ,
        0.        ],
       [0.50909658, 1.        , 0.42427158, ..., 0.        , 0.        ,
        0.        ],
       [0.80073   , 0.42427158, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.5       , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.5       ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ]])

Dormant Factor model

In [32]:
def Dormant_factor_model(ALM, AMD, k, alpha=2*10**-6, lmbda=4*10**-5, max_iter=1000):
    """
    Dormant factor model for calculating lncRNA-disease associations.

    Args:
        ALM (numpy.ndarray): Adjacency matrix of lncRNA-miRNA associations (m x n).
        AMD (numpy.ndarray): Adjacency matrix of miRNA-disease associations (n x e).
        k (int): Number of Dormant factors.
        alpha (float): Learning rate for gradient descent.
        lmbda (float): Regularization parameter.
        max_iter (int): Maximum number of iterations for gradient descent.

    Returns:
        X (numpy.ndarray): lncRNA feature matrix (m x k).
        Y (numpy.ndarray): Disease feature matrix (e x k).
        psi (numpy.ndarray): lncRNA-disease association score matrix (m x e).
    """


    # Calculate the preliminary lncRNA-disease association matrix
    ALD = ALM @ AMD

    m = ALD.shape[0]
    e = ALD.shape[1]

    # Initialize feature matrices randomly
    X = np.random.rand(m, k)
    Y = np.random.rand(e, k)

    for _ in range(max_iter):
        # Calculate the lncRNA-disease association score matrix
        psi = X @ Y.T   

        # Calculate the loss function and gradients
        # loss = np.sum((psi - ALD) ** 2) + lmbda * (np.sum(norm(X)) + np.sum(norm(Y)))
        grad_X = 2 * (psi - ALD) @ Y +  lmbda * X
        grad_Y = 2 * (psi - ALD).T @ X + lmbda * Y

        # Update feature matrices using gradient descent
        X -= alpha * grad_X
        Y -= alpha * grad_Y

    return X, Y, psi
X,Y,phi = Dormant_factor_model(LM_M,MD_M,213,max_iter=500)
X,Y,phi

(array([[ 0.01191702,  0.0386866 ,  0.33197794, ...,  0.03594867,
          0.1764851 ,  0.11321185],
        [ 0.69689107,  0.28668425,  0.41123002, ...,  0.67126637,
          0.73037112,  0.61965124],
        [ 0.20443782,  0.54822092,  0.0749367 , ...,  0.69430038,
          0.49939835,  0.33053526],
        ...,
        [ 0.76639983,  0.72775646,  0.6320432 , ...,  0.78008537,
          0.35785477,  0.07829544],
        [-0.09847617,  0.73225883, -0.01875186, ...,  0.11901569,
          0.35271883,  0.58027835],
        [ 0.62569122,  0.02386962,  0.8225404 , ...,  0.6476917 ,
         -0.14927884, -0.16236679]]),
 array([[ 0.30515233, -0.02140126, -0.04341556, ..., -0.13779668,
          0.00905075,  0.08663864],
        [ 0.29812486, -0.25151306, -0.29612048, ..., -0.06683082,
          0.07428322,  0.44376719],
        [ 0.14468103,  0.03016891, -0.15777618, ..., -0.19663191,
         -0.00244356,  0.44082574],
        ...,
        [ 0.07893211, -0.07770566,  0.06817446, ..., -

In [33]:
phi

array([[ 5.94224267,  6.47677335,  5.73609897, ...,  0.07783787,
         0.02152195,  0.48909518],
       [ 3.83224373,  5.15785515,  4.17636798, ...,  0.42371991,
        -0.13456894, -0.1996978 ],
       [ 5.98731859,  7.06253945,  5.75109301, ..., -0.54935618,
         0.53549035, -0.01763445],
       ...,
       [ 0.55481665, -0.72403102, -0.20527016, ...,  0.07630121,
        -0.18741269, -0.57744586],
       [ 0.51440134,  0.26071045,  0.82703244, ...,  0.03875945,
        -0.22994326, -0.1000076 ],
       [ 0.86026303,  0.67370645,  0.61891925, ..., -0.58928954,
        -0.60665122, -0.04617438]])

In [34]:
ILS.shape, phi.shape,len(lncRNA)

((7554, 7554), (7554, 514), 7554)

In [35]:
LP = np.zeros(shape=LD_M.shape)
for i in range(LP.shape[0]):
    for j in range(len(lncRNA)):
        LP[i,:] += ILS[i,j]*phi[j,:] 
    LP[i,:] /= norm(ILS[i:]) 
LP

array([[4.29906118e+00, 5.08886122e+00, 4.16453251e+00, ...,
        1.51421960e-01, 1.50005528e-01, 1.17502307e-01],
       [3.37434758e+00, 4.01316423e+00, 3.28474838e+00, ...,
        1.16470446e-01, 1.15594703e-01, 8.91900043e-02],
       [3.32747787e+00, 3.95816745e+00, 3.23776029e+00, ...,
        1.11379189e-01, 1.14966351e-01, 8.67072699e-02],
       ...,
       [5.78864087e+01, 6.81887781e+01, 5.56898945e+01, ...,
        1.96952013e+00, 1.87997514e+00, 1.41278304e+00],
       [1.00307961e+02, 1.17444023e+02, 9.61944397e+01, ...,
        3.74712185e+00, 3.61507852e+00, 3.21767502e+00],
       [1.55656288e+02, 1.82481898e+02, 1.48969683e+02, ...,
        5.67910253e+00, 5.38742853e+00, 4.36238766e+00]])

In [36]:
DP = np.zeros(shape=LD_M.shape)
for j in range(DP.shape[1]):
    for i in range(len(disease)):
        DP[:,j] += IDS[i,j]*phi[:,i]
    DP[:,j] /= norm(IDS[:,j])
DP

array([[ 1.10862751e+02,  1.12538664e+02,  1.11180412e+02, ...,
         4.59526331e+01,  4.59526331e+01,  2.76308771e+01],
       [ 7.61079943e+01,  7.73268393e+01,  7.62696969e+01, ...,
         3.19280111e+01,  3.19280111e+01,  1.49844256e+01],
       [ 1.12894441e+02,  1.14303152e+02,  1.12406751e+02, ...,
         4.63981872e+01,  4.63981872e+01,  1.72136273e+01],
       ...,
       [-2.12153310e+00, -2.18942975e+00, -2.06994584e+00, ...,
        -1.48113019e+00, -1.48113019e+00, -6.18786523e-01],
       [ 6.19140264e+00,  6.20456374e+00,  5.98988519e+00, ...,
         2.39894343e+00,  2.39894343e+00,  2.84519482e-02],
       [ 7.67665808e+00,  7.54358649e+00,  7.51179347e+00, ...,
         1.78878067e+00,  1.78878067e+00, -6.15146901e-01]])

In [37]:
LP.shape,DP.shape,ILS.shape,IDS.shape

((7554, 514), (7554, 514), (7554, 7554), (514, 514))

In [38]:
LFMP = np.zeros(shape=LD_M.shape)
w = 0.50
for i in range(LFMP.shape[0]):
    for j in range(LFMP.shape[1]):
        LFMP[i][j] = (w*LP[i][j] + (1-w)*DP[i][j])/(norm(ILS[i,:])+norm(IDS[:,j]))
LFMP

array([[1.7026101 , 1.74625297, 1.80980522, ..., 0.95981678, 0.95978729,
        0.63428092],
       [1.353352  , 1.39157996, 1.4510631 , ..., 0.81901119, 0.81898881,
        0.43266044],
       [2.00455692, 2.04957463, 2.13864179, ..., 1.2119855 , 1.21207897,
        0.50751623],
       ...,
       [1.75920202, 2.10051707, 1.92919743, ..., 0.04038018, 0.03297658,
        0.10168566],
       [3.1228377 , 3.65554298, 3.38377206, ..., 0.42388921, 0.41478229,
        0.31784963],
       [4.90537583, 5.75515859, 5.3240062 , ..., 0.54539731, 0.52409566,
        0.39838385]])

In [39]:
LFMP[lncRNA_index['NONHSAT006834.2']][disease_index['Ganglioneuroma']]

0.7728010596848344