In [1]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm

In [2]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [3]:
# from local system

df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [4]:

df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [5]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [6]:
dataset1

lncRNA             miRNA         Disease  PubMed ID
0    NONHSAT000612.2    hsa-miR-570-3p  Osteoarthritis   34780784
1    NONHSAT000612.2    hsa-miR-651-3p  Osteoarthritis   34780784
2    NONHSAT000612.2   hsa-miR-449b-3p  Osteoarthritis   34780784
3    NONHSAT000612.2   hsa-miR-1468-3p  Osteoarthritis   34780784
4    NONHSAT000612.2    hsa-miR-874-5p  Osteoarthritis   34780784
..               ...               ...             ...        ...
590  NONHSAT015292.2      hsa-miR-9902  Osteoarthritis   34780784
591  NONHSAT015292.2  hsa-miR-10522-5p  Osteoarthritis   34780784
592  NONHSAT015292.2  hsa-miR-10526-3p  Osteoarthritis   34780784
593  NONHSAT015292.2   hsa-miR-9851-3p  Osteoarthritis   34780784
594  NONHSAT015292.2     hsa-miR-12118  Osteoarthritis   34780784

[595 rows x 4 columns]

In [7]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [8]:
df = dataset2.copy()
df

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [9]:
df = dataset2.copy()

In [10]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [2]:
disease = [a[:-1] for a in open("./disease.txt").readlines()]
lncRNA = [a[:-1] for a in open("./lncRNA.txt").readlines()]
miRNA = [a[:-1] for a in open("./miRNA.txt").readlines()]

In [3]:
lncRNA

['NONHSAT000002.2',
 'NONHSAT000004.2',
 'NONHSAT000008.2',
 'NONHSAT000009.2',
 'NONHSAT000010.2',
 'NONHSAT000013.2',
 'NONHSAT000014.2',
 'NONHSAT000016.2',
 'NONHSAT000024.2',
 'NONHSAT000027.2',
 'NONHSAT000032.2',
 'NONHSAT000056.2',
 'NONHSAT000057.2',
 'NONHSAT000062.2',
 'NONHSAT000066.2',
 'NONHSAT000076.2',
 'NONHSAT000079.2',
 'NONHSAT000087.2',
 'NONHSAT000096.2',
 'NONHSAT000099.2',
 'NONHSAT000100.2',
 'NONHSAT000109.2',
 'NONHSAT000122.2',
 'NONHSAT000123.2',
 'NONHSAT000148.2',
 'NONHSAT000149.2',
 'NONHSAT000158.2',
 'NONHSAT000159.2',
 'NONHSAT000160.2',
 'NONHSAT000161.2',
 'NONHSAT000162.2',
 'NONHSAT000163.2',
 'NONHSAT000164.2',
 'NONHSAT000165.2',
 'NONHSAT000166.2',
 'NONHSAT000167.2',
 'NONHSAT000168.2',
 'NONHSAT000169.2',
 'NONHSAT000170.2',
 'NONHSAT000171.2',
 'NONHSAT000172.2',
 'NONHSAT000174.2',
 'NONHSAT000175.2',
 'NONHSAT000176.2',
 'NONHSAT000177.2',
 'NONHSAT000178.2',
 'NONHSAT000179.2',
 'NONHSAT000180.2',
 'NONHSAT000181.2',
 'NONHSAT000182.2',


In [12]:
# len(df['lncRNA'].unique()),len(df['miRNA'].unique()),len(df['Disease'].unique()),

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [13]:
LM_Graph = nx.Graph()
MD_Graph = nx.Graph()
LD_Graph = nx.Graph()

LM_Graph.add_nodes_from(lncRNA)
LM_Graph.add_nodes_from(miRNA)

LD_Graph.add_nodes_from(lncRNA)
LD_Graph.add_nodes_from(disease)

MD_Graph.add_nodes_from(miRNA)
MD_Graph.add_nodes_from(disease)

In [14]:
for a in df.values:
    LM_Graph.add_edge(a[0],a[1])
    MD_Graph.add_edge(a[1],a[2])
    LD_Graph.add_edge(a[0],a[2])

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [15]:
LM_index = {a:b for (a,b) in zip(LM_Graph.nodes(),range(len(LM_Graph.nodes())))}
MD_index = {a:b for (a,b) in zip(MD_Graph.nodes(),range(len(MD_Graph.nodes())))}
LD_index = {a:b for (a,b) in zip(LD_Graph.nodes(),range(len(LD_Graph.nodes())))}

In [16]:
LM_M_A = nx.adjacency_matrix(LM_Graph).todense()
MD_M_A = nx.adjacency_matrix(MD_Graph).todense()
LD_M_A = nx.adjacency_matrix(LD_Graph).todense()

In [17]:
LM_M = np.zeros(shape=(len(lncRNA),len(miRNA)))
MD_M = np.zeros(shape=(len(miRNA), len(disease)))
LD_M = np.zeros(shape=(len(lncRNA), len(disease)))

In [18]:
for a in range(len(lncRNA)):
    for b in range(len(miRNA)):
        LM_M[a][b] = LM_M_A[LM_index[lncRNA[a]]][LM_index[miRNA[b]]]
LM_M

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
for a in range(len(miRNA)):
    for b in range(len(disease)):
        MD_M[a][b] = MD_M_A[MD_index[miRNA[a]]][MD_index[disease[b]]]
MD_M

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
LD = LM_M.dot(MD_M)
LD

array([[5., 6., 6., ..., 0., 0., 0.],
       [3., 5., 5., ..., 0., 0., 0.],
       [7., 9., 7., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
# # run this if CD.csv is not found in the current folder
# CD = np.zeros(shape=(len(disease),len(disease)))
# for i in range(len(disease)):
#     for j in range(len(disease)):
#         CD[i][j] = (LD[:,i].dot(LD[:,j]))/(norm(LD[:,i])*norm(LD[:,j]))
# np.savetxt("CD.csv",CD,delimiter=',',fmt='%.5f')

In [22]:
CD = np.loadtxt("CD.csv",delimiter=',',dtype=float)

In [23]:
# # run this if CL.csv not found in the current folder
# CL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
# for i in range(len(lncRNA)):
#     for j in range(len(lncRNA)):
#         CL[i][j] = (LD[i,:].dot(LD[j,:]))/(norm(LD[i,:])*norm(LD[j,:]))
# np.savetxt("CL.csv",CL,delimiter=',',fmt="%.5f")

In [24]:
CL = np.loadtxt("./CL.csv",delimiter=',',dtype=float)

In [25]:
LD.shape

(7554, 514)

In [26]:
CD.shape

(514, 514)

In [27]:
LD_New = np.zeros(shape=LD.shape)

In [28]:
for j in range(0,len(disease)):
    for i in range(0,len(disease)):
        # print(i,j)
        LD_New[:,j] += CD[i][j]*LD[:,j]
LD_New 

array([[2266.6889 , 2745.24786, 2727.36414, ...,    0.     ,    0.     ,
           0.     ],
       [1360.01334, 2287.70655, 2272.80345, ...,    0.     ,    0.     ,
           0.     ],
       [3173.36446, 4117.87179, 3181.92483, ...,    0.     ,    0.     ,
           0.     ],
       ...,
       [   0.     ,    0.     ,    0.     , ...,    0.     ,    0.     ,
           0.     ],
       [   0.     ,    0.     ,    0.     , ...,    0.     ,    0.     ,
           0.     ],
       [   0.     ,    0.     ,    0.     , ...,    0.     ,    0.     ,
           0.     ]])

In [29]:
for j in range(0,len(lncRNA)):
    for i in range(0,len(lncRNA)):
        # print(i,j)
        LD_New[j,:] += CL[i][j]*LD[j,:]

In [31]:
LD_New

array([[37414.4238 , 44922.52974, 44904.64602, ...,     0.     ,
            0.     ,     0.     ],
       [22044.7497 , 36762.26715, 36747.36405, ...,     0.     ,
            0.     ,     0.     ],
       [47579.63427, 61211.64726, 47588.19464, ...,     0.     ,
            0.     ,     0.     ],
       ...,
       [    0.     ,     0.     ,     0.     , ...,     0.     ,
            0.     ,     0.     ],
       [    0.     ,     0.     ,     0.     , ...,     0.     ,
            0.     ,     0.     ],
       [    0.     ,     0.     ,     0.     , ...,     0.     ,
            0.     ,     0.     ]])