In [1]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm

In [2]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [3]:
# from local system

df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [4]:

df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [5]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [6]:
# dataset1

In [7]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [8]:
df = dataset2.copy()
# df

In [9]:
df = dataset2.copy()

In [10]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [11]:
disease = [a[:-1] for a in open("./disease.txt").readlines()]
lncRNA = [a[:-1] for a in open("./lncRNA.txt").readlines()]
miRNA = [a[:-1] for a in open("./miRNA.txt").readlines()]

In [12]:
len(lncRNA),len(miRNA),len(disease)

(7554, 239, 514)

In [13]:
lncRNA_index = {a:b for (a,b) in zip(lncRNA,range(len(lncRNA)))}
disease_index = {a:b for (a,b) in zip(disease,range(len(disease)))}
miRNA_index = {a:b for (a,b) in zip(miRNA,range(len(miRNA)))}

In [14]:
# len(df['lncRNA'].unique()),len(df['miRNA'].unique()),len(df['Disease'].unique()),

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [15]:
LM_Graph = nx.Graph()
MD_Graph = nx.Graph()
LD_Graph = nx.Graph()

LM_Graph.add_nodes_from(lncRNA)
LM_Graph.add_nodes_from(miRNA)

LD_Graph.add_nodes_from(lncRNA)
LD_Graph.add_nodes_from(disease)

MD_Graph.add_nodes_from(miRNA)
MD_Graph.add_nodes_from(disease)

In [16]:
for a in df.values:
    LM_Graph.add_edge(a[0],a[1])
    MD_Graph.add_edge(a[1],a[2])
    LD_Graph.add_edge(a[0],a[2])

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [17]:
LM_index = {a:b for (a,b) in zip(LM_Graph.nodes(),range(len(LM_Graph.nodes())))}
MD_index = {a:b for (a,b) in zip(MD_Graph.nodes(),range(len(MD_Graph.nodes())))}
LD_index = {a:b for (a,b) in zip(LD_Graph.nodes(),range(len(LD_Graph.nodes())))}

In [18]:
LM_M_A = nx.adjacency_matrix(LM_Graph).todense()
MD_M_A = nx.adjacency_matrix(MD_Graph).todense()
LD_M_A = nx.adjacency_matrix(LD_Graph).todense()

In [19]:
LM_M = np.zeros(shape=(len(lncRNA),len(miRNA)),dtype=int)
MD_M = np.zeros(shape=(len(miRNA), len(disease)),dtype=int)
LD_M = np.zeros(shape=(len(lncRNA), len(disease)),dtype=int)

In [20]:
for a in range(len(lncRNA)):
    for b in range(len(disease)):
        LD_M[a][b] = LD_M_A[LD_index[lncRNA[a]]][LD_index[disease[b]]]
LD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
for a in range(len(lncRNA)):
    for b in range(len(miRNA)):
        LM_M[a][b] = LM_M_A[LM_index[lncRNA[a]]][LM_index[miRNA[b]]]
LM_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
for a in range(len(miRNA)):
    for b in range(len(disease)):
        MD_M[a][b] = MD_M_A[MD_index[miRNA[a]]][MD_index[disease[b]]]
MD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
LD = LM_M.dot(MD_M)
LD

array([[5, 6, 6, ..., 0, 0, 0],
       [3, 5, 5, ..., 0, 0, 0],
       [7, 9, 7, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
# # run this if CD.csv is not found in the current folder(runs for seconds)
# CD = np.zeros(shape=(len(disease),len(disease)))
# for i in range(len(disease)):
#     for j in range(len(disease)):
#         CD[i][j] = (MD_M[:,i].dot(MD_M[:,j]))/(norm(MD_M[:,i])*norm(MD_M[:,j]))
# np.save("CD",CD)

In [25]:
CD = np.load("CD.npy")

In [26]:
# # run this if CL.csv not found in the current folder(run for 8 min )
# CL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
# for i in range(len(lncRNA)):
#     for j in range(len(lncRNA)):
#         CL[i][j] = (LM_M[i,:].dot(LM_M[j,:]))/(norm(LM_M[i,:])*norm(LM_M[j,:]))
# np.save("CL",CL)

In [27]:
CL = np.load("CL.npy")

In [28]:
JD = np.zeros(shape=CD.shape)
for i in range(MD_M.shape[-1]):
    for j in range(MD_M.shape[-1]):
        JD[i][j] =(np.bitwise_and(MD_M[:,i],MD_M[:,j]).sum())/(np.bitwise_or(MD_M[:,i],MD_M[:,j]).sum())
        

In [29]:
JL = np.zeros(shape=CL.shape)
for i in range(LM_M.shape[-1]):
    for j in range(LM_M.shape[-1]):
        JL[i][j] =(np.bitwise_and(LM_M[:,i],LM_M[:,j]).sum())/(np.bitwise_or(LM_M[:,i],LM_M[:,j]).sum())
JL      

array([[1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.28849315, 1.        , 0.28849315, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
IDS = np.zeros(shape=CD.shape)
for i in range(IDS.shape[0]):
    for j in range(IDS.shape[-1]):
        if CD[i][j] == 0:
            IDS[i][j] = JD[i][j]
        else:
            IDS[i][j] = (CD[i][j]+JD[i][j])/2
IDS

array([[1.        , 0.73534833, 0.62628227, ..., 0.        , 0.        ,
        0.        ],
       [0.73534833, 1.        , 0.79003636, ..., 0.19620955, 0.19620955,
        0.        ],
       [0.62628227, 0.79003636, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.19620955, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.19620955, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [31]:
ILS = np.zeros(shape=CL.shape)
for i in range(ILS.shape[0]):
    for j in range(ILS.shape[-1]):
        if CL[i][j] == 0:
            ILS[i][j] = JL[i][j]
        else:
            ILS[i][j] = (CL[i][j]+JL[i][j])/2
ILS

array([[1.        , 0.50909658, 0.80073   , ..., 0.        , 0.        ,
        0.        ],
       [0.50909658, 1.        , 0.42427158, ..., 0.        , 0.        ,
        0.        ],
       [0.80073   , 0.42427158, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.5       , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.5       ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ]])

Dormant Factor model

In [32]:
def Dormant_factor_model(ALM, AMD, k, alpha=2*10**-6, lmbda=4*10**-5, max_iter=1000):
    """
    Dormant factor model for calculating lncRNA-disease associations.

    Args:
        ALM (numpy.ndarray): Adjacency matrix of lncRNA-miRNA associations (m x n).
        AMD (numpy.ndarray): Adjacency matrix of miRNA-disease associations (n x e).
        k (int): Number of Dormant factors.
        alpha (float): Learning rate for gradient descent.
        lmbda (float): Regularization parameter.
        max_iter (int): Maximum number of iterations for gradient descent.

    Returns:
        X (numpy.ndarray): lncRNA feature matrix (m x k).
        Y (numpy.ndarray): Disease feature matrix (e x k).
        psi (numpy.ndarray): lncRNA-disease association score matrix (m x e).
    """


    # Calculate the preliminary lncRNA-disease association matrix
    ALD = ALM @ AMD

    m = ALD.shape[0]
    e = ALD.shape[1]

    # Initialize feature matrices randomly
    X = np.random.rand(m, k)
    Y = np.random.rand(e, k)

    for _ in range(max_iter):
        # Calculate the lncRNA-disease association score matrix
        psi = X @ Y.T   

        # Calculate the loss function and gradients
        # loss = np.sum((psi - ALD) ** 2) + lmbda * (np.sum(norm(X)) + np.sum(norm(Y)))
        grad_X = 2 * (psi - ALD) @ Y +  lmbda * X
        grad_Y = 2 * (psi - ALD).T @ X + lmbda * Y

        # Update feature matrices using gradient descent
        X -= alpha * grad_X
        Y -= alpha * grad_Y

    return X, Y, psi
X,Y,phi = Dormant_factor_model(LM_M,MD_M,213,max_iter=500)
X,Y,phi

(array([[ 0.74943973,  0.16278232,  0.87225361, ...,  0.02117704,
          0.53730018,  0.80541117],
        [ 0.7858517 ,  0.33006347,  0.40558154, ...,  0.43545066,
          0.05370447,  0.49769065],
        [ 0.39957034,  0.14820875,  0.53748987, ...,  1.02138269,
          0.51230775,  0.33616891],
        ...,
        [-0.13763904,  0.39275231,  0.48132039, ...,  0.64508244,
          0.25925785,  0.08503762],
        [ 0.49711394,  0.64953417,  0.86149657, ...,  0.28144923,
          0.05681169,  0.19346783],
        [ 0.73514957,  0.0877606 ,  0.27549415, ...,  0.66543819,
          0.04151243,  0.0821251 ]]),
 array([[ 0.10770788,  0.39112638,  0.17662209, ...,  0.179232  ,
          0.0311253 , -0.03192937],
        [ 0.10654091,  0.49312942,  0.19723677, ...,  0.0589919 ,
          0.08792341,  0.19706244],
        [ 0.21029022,  0.26439492,  0.15538088, ...,  0.02119579,
          0.10428741, -0.11401015],
        ...,
        [-0.06049591, -0.02979216,  0.10920256, ...,  

In [40]:
phi.max()

211.27496490291148

In [34]:
ILS.shape, phi.shape,len(lncRNA)

((7554, 7554), (7554, 514), 7554)

In [35]:
LP = np.zeros(shape=LD_M.shape)
for i in range(LP.shape[0]):
    for j in range(len(lncRNA)):
        LP[i,:] += ILS[i,j]*phi[j,:] 
    LP[i,:] /= norm(ILS[i:]) 
LP

array([[4.30098021e+00, 5.08401718e+00, 4.16334663e+00, ...,
        1.51539816e-01, 1.48697530e-01, 1.18277508e-01],
       [3.37842254e+00, 4.01689894e+00, 3.28451367e+00, ...,
        1.17577051e-01, 1.17419987e-01, 8.79477621e-02],
       [3.33121736e+00, 3.96736397e+00, 3.23940668e+00, ...,
        1.17140045e-01, 1.15546068e-01, 8.70959328e-02],
       ...,
       [5.74850371e+01, 6.80406724e+01, 5.57761169e+01, ...,
        1.90468057e+00, 2.03926698e+00, 1.89670569e+00],
       [9.99716399e+01, 1.17119542e+02, 9.56488226e+01, ...,
        3.37277022e+00, 3.22146583e+00, 3.02462107e+00],
       [1.55439325e+02, 1.81658487e+02, 1.49476691e+02, ...,
        5.51297000e+00, 5.14735909e+00, 4.19257422e+00]])

In [36]:
DP = np.zeros(shape=LD_M.shape)
for j in range(DP.shape[1]):
    for i in range(len(disease)):
        DP[:,j] += IDS[i,j]*phi[:,i]
    DP[:,j] /= norm(IDS[:,j])
DP

array([[ 1.02135511e+02,  1.03539931e+02,  1.02145111e+02, ...,
         4.27066041e+01,  4.27066041e+01,  2.75582693e+01],
       [ 6.66161670e+01,  6.75194015e+01,  6.65873537e+01, ...,
         2.73701243e+01,  2.73701243e+01,  1.45369805e+01],
       [ 1.14790005e+02,  1.16384680e+02,  1.14497498e+02, ...,
         4.75685978e+01,  4.75685978e+01,  1.74845164e+01],
       ...,
       [ 1.22179041e+00,  1.28993987e+00,  1.23280738e+00, ...,
         9.75699841e-01,  9.75699841e-01,  7.73258798e-01],
       [ 8.98121622e-02, -1.02554619e-01,  1.08043712e-01, ...,
        -1.13493197e+00, -1.13493197e+00,  8.29865524e-01],
       [ 1.96532351e+00,  1.86298531e+00,  2.05126185e+00, ...,
         6.76599344e-01,  6.76599344e-01, -3.96168734e-01]])

In [37]:
LP.shape,DP.shape,ILS.shape,IDS.shape

((7554, 514), (7554, 514), (7554, 7554), (514, 514))

In [41]:
LP.max(),DP.max(),ILS.max(),IDS.max()

(3735.024311768044, 436.49419488534625, 1.0, 1.0)

In [38]:
LFMP = np.zeros(shape=LD_M.shape)
w = 0.50
for i in range(LFMP.shape[0]):
    for j in range(LFMP.shape[1]):
        LFMP[i][j] = (w*LP[i][j] + (1-w)*DP[i][j])/(norm(ILS[i,:])+norm(IDS[:,j]))
LFMP

array([[1.57361057, 1.61258933, 1.66801937, ..., 0.89224181, 0.89218264,
        0.63263895],
       [1.1918033 , 1.22385638, 1.2744541 , ..., 0.7025464 , 0.70254238,
        0.41978169],
       [2.03731548, 2.08580876, 2.17733692, ..., 1.24263517, 1.24259363,
        0.51547434],
       ...,
       [1.85201112, 2.20653897, 2.05112972, ..., 0.23815046, 0.24927809,
        0.34193741],
       [2.93406143, 3.45948658, 3.17093066, ..., 0.15434192, 0.14390657,
        0.37741812],
       [4.72733137, 5.55817647, 5.15547132, ..., 0.452039  , 0.42533757,
        0.40361074]])

In [39]:
LFMP[lncRNA_index['NONHSAT006834.2']][disease_index['Ganglioneuroma']]

0.783437993281654

In [43]:
Y0 = np.load("Y0.npy")

In [44]:
LPm = np.zeros(shape=LD_M.shape)
for i in range(LPm.shape[0]):
    for j in range(len(lncRNA)):
        LPm[i,:] += ILS[i,j]*Y0[j,:] 
    LPm[i,:] /= norm(ILS[i:]) 
LPm

array([[ 0.81016502,  0.8072302 ,  0.80537239, ...,  0.7383488 ,
         0.7383488 ,  0.71459042],
       [ 0.62532744,  0.62467607,  0.62336949, ...,  0.57150404,
         0.57150404,  0.55272242],
       [ 0.60989888,  0.60931681,  0.6080668 , ...,  0.55631532,
         0.55631532,  0.53801437],
       ...,
       [10.46019253, 10.54085864, 10.50362197, ...,  9.62646597,
         9.62646597,  9.35084047],
       [19.45956283, 19.43959248, 19.40954025, ..., 17.63553771,
        17.63553771, 17.21338006],
       [29.81184733, 29.49077544, 29.44139569, ..., 26.91128819,
        26.91128819, 26.32312207]])

In [45]:
DPm = np.zeros(shape=LD_M.shape)
for j in range(DPm.shape[1]):
    for i in range(len(disease)):
        DPm[:,j] += IDS[i,j]*Y0[:,i]
    DPm[:,j] /= norm(IDS[:,j])
DPm

array([[12.93114781, 12.77789704, 13.1713032 , ...,  5.55126836,
         5.55126836,  1.20903147],
       [12.96262795, 12.79680171, 13.2021947 , ...,  5.51272462,
         5.51272462,  1.19689106],
       [12.93537201, 12.77276961, 13.1713032 , ...,  5.52070626,
         5.52070626,  1.20412996],
       ...,
       [ 2.64147623,  2.61247731,  2.71997823, ...,  1.04358586,
         1.04358586,  0.32607128],
       [ 3.09248913,  3.05739487,  3.19210636, ...,  1.21290166,
         1.21290166,  0.45487799],
       [ 2.17200424,  2.14334835,  2.21932211, ...,  0.84484799,
         0.84484799,  0.17652873]])

In [46]:
LPm.max(),DPm.max()

(34.920183260590115, 15.218701334972156)

In [50]:
LFMPm = np.zeros(shape=LD_M.shape)
w = 0.50
for i in range(LFMP.shape[0]):
    for j in range(LFMP.shape[1]):
        LFMPm[i][j] = (w*LPm[i][j] + (1-w)*DPm[i][j])/(norm(ILS[i,:])+norm(IDS[:,j]))
LFMPm

array([[0.20315847, 0.20167957, 0.21929926, ..., 0.13094033, 0.13094033,
        0.04397074],
       [0.23136317, 0.22961715, 0.25217656, ..., 0.1555042 , 0.1555042 ,
        0.05021944],
       [0.23362432, 0.23192355, 0.25482521, ..., 0.15836015, 0.15836015,
        0.0511069 ],
       ...,
       [0.4133154 , 0.41862242, 0.47577322, ..., 0.88220214, 0.88220214,
        1.23930418],
       [0.66128468, 0.66510024, 0.74843985, ..., 1.2999618 , 1.2999618 ,
        1.73001527],
       [0.96057052, 0.95807886, 1.07720008, ..., 2.02709678, 2.02709678,
        2.8172817 ]])

In [51]:
LFMPm.max(),LFMPm.min()

(3.589902032078606, 0.03849203791699931)