In [55]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm

In [56]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [57]:
# from local system

df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [58]:

df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [59]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [60]:
dataset1

lncRNA             miRNA         Disease  PubMed ID
0    NONHSAT000612.2    hsa-miR-570-3p  Osteoarthritis   34780784
1    NONHSAT000612.2    hsa-miR-651-3p  Osteoarthritis   34780784
2    NONHSAT000612.2   hsa-miR-449b-3p  Osteoarthritis   34780784
3    NONHSAT000612.2   hsa-miR-1468-3p  Osteoarthritis   34780784
4    NONHSAT000612.2    hsa-miR-874-5p  Osteoarthritis   34780784
..               ...               ...             ...        ...
590  NONHSAT015292.2      hsa-miR-9902  Osteoarthritis   34780784
591  NONHSAT015292.2  hsa-miR-10522-5p  Osteoarthritis   34780784
592  NONHSAT015292.2  hsa-miR-10526-3p  Osteoarthritis   34780784
593  NONHSAT015292.2   hsa-miR-9851-3p  Osteoarthritis   34780784
594  NONHSAT015292.2     hsa-miR-12118  Osteoarthritis   34780784

[595 rows x 4 columns]

In [61]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [62]:
df = dataset2.copy()
df

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [63]:
df = dataset2.copy()

In [64]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [65]:
disease = [a[:-1] for a in open("./disease.txt").readlines()]
lncRNA = [a[:-1] for a in open("./lncRNA.txt").readlines()]
miRNA = [a[:-1] for a in open("./miRNA.txt").readlines()]

In [66]:
# len(df['lncRNA'].unique()),len(df['miRNA'].unique()),len(df['Disease'].unique()),

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [67]:
LM_Graph = nx.Graph()
MD_Graph = nx.Graph()
LD_Graph = nx.Graph()

LM_Graph.add_nodes_from(lncRNA)
LM_Graph.add_nodes_from(miRNA)

LD_Graph.add_nodes_from(lncRNA)
LD_Graph.add_nodes_from(disease)

MD_Graph.add_nodes_from(miRNA)
MD_Graph.add_nodes_from(disease)

In [68]:
for a in df.values:
    LM_Graph.add_edge(a[0],a[1])
    MD_Graph.add_edge(a[1],a[2])
    LD_Graph.add_edge(a[0],a[2])

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [69]:
LM_index = {a:b for (a,b) in zip(LM_Graph.nodes(),range(len(LM_Graph.nodes())))}
MD_index = {a:b for (a,b) in zip(MD_Graph.nodes(),range(len(MD_Graph.nodes())))}
LD_index = {a:b for (a,b) in zip(LD_Graph.nodes(),range(len(LD_Graph.nodes())))}

In [70]:
LM_M_A = nx.adjacency_matrix(LM_Graph).todense()
MD_M_A = nx.adjacency_matrix(MD_Graph).todense()
LD_M_A = nx.adjacency_matrix(LD_Graph).todense()

In [71]:
LM_M = np.zeros(shape=(len(lncRNA),len(miRNA)),dtype=int)
MD_M = np.zeros(shape=(len(miRNA), len(disease)),dtype=int)
LD_M = np.zeros(shape=(len(lncRNA), len(disease)),dtype=int)

In [134]:
for a in range(len(lncRNA)):
    for b in range(len(disease)):
        LD_M[a][b] = LD_M_A[LD_index[lncRNA[a]]][LD_index[disease[b]]]
LD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [72]:
for a in range(len(lncRNA)):
    for b in range(len(miRNA)):
        LM_M[a][b] = LM_M_A[LM_index[lncRNA[a]]][LM_index[miRNA[b]]]
LM_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [73]:
for a in range(len(miRNA)):
    for b in range(len(disease)):
        MD_M[a][b] = MD_M_A[MD_index[miRNA[a]]][MD_index[disease[b]]]
MD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [74]:
LD = LM_M.dot(MD_M)
LD

array([[5, 6, 6, ..., 0, 0, 0],
       [3, 5, 5, ..., 0, 0, 0],
       [7, 9, 7, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [75]:
# # run this if CD.csv is not found in the current folder
# CD = np.zeros(shape=(len(disease),len(disease)))
# for i in range(len(disease)):
#     for j in range(len(disease)):
#         CD[i][j] = (LD[:,i].dot(LD[:,j]))/(norm(LD[:,i])*norm(LD[:,j]))
# np.savetxt("CD.csv",CD,delimiter=',',fmt='%.5f')

In [76]:
CD = np.loadtxt("CD.csv",delimiter=',',dtype=float)

In [77]:
# # run this if CL.csv not found in the current folder
# CL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
# for i in range(len(lncRNA)):
#     for j in range(len(lncRNA)):
#         CL[i][j] = (LD[i,:].dot(LD[j,:]))/(norm(LD[i,:])*norm(LD[j,:]))
# np.savetxt("CL.csv",CL,delimiter=',',fmt="%.5f")

In [78]:
CL = np.loadtxt("./CL.csv",delimiter=',',dtype=float)

In [79]:
JD = np.zeros(shape=CD.shape)
for i in range(MD_M.shape[-1]):
    for j in range(MD_M.shape[-1]):
        JD[i][j] =(np.bitwise_and(MD_M[:,i],MD_M[:,j]).sum())/(np.bitwise_or(MD_M[:,i],MD_M[:,j]).sum())
        

In [80]:
JL = np.zeros(shape=CL.shape)
for i in range(LM_M.shape[-1]):
    for j in range(LM_M.shape[-1]):
        JL[i][j] =(np.bitwise_and(LM_M[:,i],LM_M[:,j]).sum())/(np.bitwise_or(LM_M[:,i],LM_M[:,j]).sum())
JL      

array([[1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.28849315, 1.        , 0.28849315, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [81]:
IDS = np.zeros(shape=CD.shape)
for i in range(IDS.shape[0]):
    for j in range(IDS.shape[-1]):
        if CD[i][j] == 0:
            IDS[i][j] = JD[i][j]
        else:
            IDS[i][j] = (CD[i][j]+JD[i][j])/2
IDS

array([[1.        , 0.81975833, 0.73970227, ..., 0.17259   , 0.17259   ,
        0.150645  ],
       [0.81975833, 1.        , 0.85354136, ..., 0.24611955, 0.24611955,
        0.14695   ],
       [0.73970227, 0.85354136, 1.        , ..., 0.17002   , 0.17002   ,
        0.14324   ],
       ...,
       [0.17259   , 0.24611955, 0.17002   , ..., 1.        , 1.        ,
        0.091245  ],
       [0.17259   , 0.24611955, 0.17002   , ..., 1.        , 1.        ,
        0.091245  ],
       [0.150645  , 0.14695   , 0.14324   , ..., 0.091245  , 0.091245  ,
        1.        ]])

In [82]:
ILS = np.zeros(shape=CL.shape)
for i in range(ILS.shape[0]):
    for j in range(ILS.shape[-1]):
        if CL[i][j] == 0:
            ILS[i][j] = JL[i][j]
        else:
            ILS[i][j] = (CL[i][j]+JL[i][j])/2
ILS

array([[1.        , 0.63924158, 0.963005  , ..., 0.31482   , 0.4182    ,
        0.282695  ],
       [0.63924158, 1.        , 0.62178658, ..., 0.298965  , 0.401295  ,
        0.269725  ],
       [0.963005  , 0.62178658, 1.        , ..., 0.253995  , 0.330115  ,
        0.2033    ],
       ...,
       [0.31482   , 0.298965  , 0.253995  , ..., 0.5       , 0.27778   ,
        0.175035  ],
       [0.4182    , 0.401295  , 0.330115  , ..., 0.27778   , 0.5       ,
        0.303395  ],
       [0.282695  , 0.269725  , 0.2033    , ..., 0.175035  , 0.303395  ,
        0.5       ]])

Latent Factor model

In [130]:
def latent_factor_model(ALM, AMD, k, alpha=2*10**-6, lmbda=4*10**-5, max_iter=1000):
    """
    Latent factor model for calculating lncRNA-disease associations.

    Args:
        ALM (numpy.ndarray): Adjacency matrix of lncRNA-miRNA associations (m x n).
        AMD (numpy.ndarray): Adjacency matrix of miRNA-disease associations (n x e).
        k (int): Number of latent factors.
        alpha (float): Learning rate for gradient descent.
        lmbda (float): Regularization parameter.
        max_iter (int): Maximum number of iterations for gradient descent.

    Returns:
        X (numpy.ndarray): lncRNA feature matrix (m x k).
        Y (numpy.ndarray): Disease feature matrix (e x k).
        psi (numpy.ndarray): lncRNA-disease association score matrix (m x e).
    """


    # Calculate the preliminary lncRNA-disease association matrix
    ALD = ALM @ AMD

    m = ALD.shape[0]
    e = ALD.shape[1]

    # Initialize feature matrices randomly
    X = np.random.rand(m, k)
    Y = np.random.rand(e, k)

    for _ in range(max_iter):
        # Calculate the lncRNA-disease association score matrix
        psi = X @ Y.T

        # Calculate the loss function and gradients
        loss = np.sum((psi - ALD) ** 2) + lmbda * (np.sum(norm(X)) + np.sum(norm(Y)))
        grad_X = 2 * (psi - ALD) @ Y + 2 * lmbda * X
        grad_Y = 2 * (psi - ALD).T @ X + 2 * lmbda * Y

        # Update feature matrices using gradient descent
        X -= alpha * grad_X
        Y -= alpha * grad_Y

    return X, Y, psi
X,Y,phi = latent_factor_model(LM_M,MD_M,213,max_iter=500)
# X,Y,phi

In [141]:
phi

array([[ 5.04307391,  6.8106402 ,  5.3108733 , ...,  0.23732803,
         0.73422532, -0.00866631],
       [ 3.25896682,  3.98790537,  3.59844004, ..., -0.47685127,
        -0.10271954,  0.04393911],
       [ 6.56667558,  8.4096153 ,  7.09125296, ...,  0.12164229,
         0.2910935 ,  0.44860718],
       ...,
       [-0.43006073, -0.33744549,  0.33670867, ..., -0.74228556,
        -0.01788368,  0.19991128],
       [-0.47668193,  0.3375808 , -0.46468845, ...,  0.19381498,
        -0.85246599, -0.33816856],
       [ 0.18308249,  0.43003865, -0.18510584, ..., -0.43529421,
        -0.37868488, -0.57157002]])

In [139]:
phi.shape

(7554, 514)

In [140]:
LD_M.shape

(7554, 514)