In [1]:
import pandas as pd
import numpy as np
import networkx as nx 
from numpy.linalg import norm

In [2]:
# # from colab run this 
# !git clone https://github.com/gru13/lncRNA_Disease_association.git
# df_lnc_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/lncrnaDiesease3/website_alldata_p1.csv")
# df_lnc_mir = pd.read_csv(r"./lncRNA_Disease_association/datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
# df_mir_die = pd.read_csv(r"./lncRNA_Disease_association/datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")

In [3]:
# from local system

df_lnc_die = pd.read_csv(r"./../datasets/lncrnaDiesease3/website_alldata_p1.csv")
df_lnc_mir = pd.read_csv(r"./../datasets/LncRNASNP/Homo_sapiens_lncRNA_miRNA_interactions.csv")
df_mir_die = pd.read_csv(r"./../datasets/rnaDisease/RNADisease_RNA-disease_miRNA_predict.csv")


In [4]:

df_lnc_die.head(),df_lnc_mir.head(),df_mir_die.head()

(        lncRNA                    Disease  PubMed ID
 0  ARHGAP5-AS1  Carcinoma, Hepatocellular   36354136
 1       HOTTIP               Osteosarcoma   33475442
 2       HOTTIP                     Glioma   35402278
 3       HOTTIP             Retinoblastoma   33784880
 4       HOTTIP          stomach carcinoma   32633359,
             lncRNA           miRNA
 0  NONHSAT000002.2  hsa-miR-15a-5p
 1  NONHSAT000002.2  hsa-miR-15a-3p
 2  NONHSAT000002.2   hsa-miR-16-5p
 3  NONHSAT000002.2   hsa-miR-21-3p
 4  NONHSAT000002.2   hsa-miR-28-5p,
           miRNA                    Disease
 0  hsa-let-7a-1  Abdominal aortic aneurysm
 1  hsa-let-7a-2  Abdominal aortic aneurysm
 2  hsa-let-7a-3  Abdominal aortic aneurysm
 3    hsa-let-7c  Abdominal aortic aneurysm
 4    hsa-let-7d  Abdominal aortic aneurysm)

In [5]:
dataset1 = pd.merge(df_lnc_mir,df_lnc_die,on=['lncRNA'],how='inner')
dataset2 = pd.merge(df_lnc_mir,df_mir_die,on=['miRNA'],how='inner')

In [6]:
# dataset1

In [7]:
dataset2

lncRNA           miRNA                             Disease
0        NONHSAT000002.2  hsa-miR-15a-5p                   Abortion habitual
1        NONHSAT000002.2  hsa-miR-15a-5p                    Acoustic neuroma
2        NONHSAT000002.2  hsa-miR-15a-5p  Acquired immunodeficiency syndrome
3        NONHSAT000002.2  hsa-miR-15a-5p             Acute coronary syndrome
4        NONHSAT000002.2  hsa-miR-15a-5p                Acute kidney failure
...                  ...             ...                                 ...
9376652  NONHSAT017163.2  hsa-miR-523-3p             Intellectual disability
9376653  NONHSAT017163.2  hsa-miR-523-3p                            Leukemia
9376654  NONHSAT017163.2  hsa-miR-523-3p          Neurodegenerative diseases
9376655  NONHSAT017163.2  hsa-miR-523-3p                        Skin disease
9376656  NONHSAT017163.2  hsa-miR-523-3p                   Vascular diseases

[9376657 rows x 3 columns]

In [8]:
df = dataset2.copy()
# df

In [9]:
df = dataset2.copy()

In [10]:
# # only run this for first time 
# disease = df['Disease'].unique()
# lncRNA = df['lncRNA'].unique()
# miRNA = df['miRNA'].unique()

# np.savetxt("./disease.txt",disease,delimiter=',',fmt='%s')
# np.savetxt("./lncRNA.txt",lncRNA,delimiter=',',fmt='%s')
# np.savetxt("./miRNA.txt",miRNA,delimiter=',',fmt='%s')

In [11]:
disease = [a[:-1] for a in open("./disease.txt").readlines()]
lncRNA = [a[:-1] for a in open("./lncRNA.txt").readlines()]
miRNA = [a[:-1] for a in open("./miRNA.txt").readlines()]

In [12]:
lncRNA_index = {a:b for (a,b) in zip(lncRNA,range(len(lncRNA)))}
disease_index = {a:b for (a,b) in zip(disease,range(len(disease)))}
miRNA_index = {a:b for (a,b) in zip(miRNA,range(len(miRNA)))}

In [13]:
# len(df['lncRNA'].unique()),len(df['miRNA'].unique()),len(df['Disease'].unique()),

CReation of the graph that contains the totaly connected with miRNA, lncRNA, Disease

In [14]:
LM_Graph = nx.Graph()
MD_Graph = nx.Graph()
LD_Graph = nx.Graph()

LM_Graph.add_nodes_from(lncRNA)
LM_Graph.add_nodes_from(miRNA)

LD_Graph.add_nodes_from(lncRNA)
LD_Graph.add_nodes_from(disease)

MD_Graph.add_nodes_from(miRNA)
MD_Graph.add_nodes_from(disease)

In [15]:
for a in df.values:
    LM_Graph.add_edge(a[0],a[1])
    MD_Graph.add_edge(a[1],a[2])
    LD_Graph.add_edge(a[0],a[2])

CReation of the Lncrna-disease , Lncrna-miRNA, miRNA-Disease assoction matrix (LM,LD,MD)

In [16]:
LM_index = {a:b for (a,b) in zip(LM_Graph.nodes(),range(len(LM_Graph.nodes())))}
MD_index = {a:b for (a,b) in zip(MD_Graph.nodes(),range(len(MD_Graph.nodes())))}
LD_index = {a:b for (a,b) in zip(LD_Graph.nodes(),range(len(LD_Graph.nodes())))}

In [17]:
LM_M_A = nx.adjacency_matrix(LM_Graph).todense()
MD_M_A = nx.adjacency_matrix(MD_Graph).todense()
LD_M_A = nx.adjacency_matrix(LD_Graph).todense()

In [18]:
LM_M = np.zeros(shape=(len(lncRNA),len(miRNA)),dtype=int)
MD_M = np.zeros(shape=(len(miRNA), len(disease)),dtype=int)
LD_M = np.zeros(shape=(len(lncRNA), len(disease)),dtype=int)

In [19]:
for a in range(len(lncRNA)):
    for b in range(len(disease)):
        LD_M[a][b] = LD_M_A[LD_index[lncRNA[a]]][LD_index[disease[b]]]
LD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
for a in range(len(lncRNA)):
    for b in range(len(miRNA)):
        LM_M[a][b] = LM_M_A[LM_index[lncRNA[a]]][LM_index[miRNA[b]]]
LM_M

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
for a in range(len(miRNA)):
    for b in range(len(disease)):
        MD_M[a][b] = MD_M_A[MD_index[miRNA[a]]][MD_index[disease[b]]]
MD_M

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
LD = LM_M.dot(MD_M)
LD

array([[5, 6, 6, ..., 0, 0, 0],
       [3, 5, 5, ..., 0, 0, 0],
       [7, 9, 7, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
# # run this if CD.csv is not found in the current folder(runs for seconds)
# CD = np.zeros(shape=(len(disease),len(disease)))
# for i in range(len(disease)):
#     for j in range(len(disease)):
#         CD[i][j] = (MD_M[:,i].dot(MD_M[:,j]))/(norm(MD_M[:,i])*norm(MD_M[:,j]))
# np.savetxt("CD.csv",CD,delimiter=',',fmt='%.5f')

In [24]:
CD = np.loadtxt("CD.csv",delimiter=',',dtype=float)

In [25]:
# # run this if CL.csv not found in the current folder(run for 8 min )
# CL = np.zeros(shape=(len(lncRNA),len(lncRNA)))
# for i in range(len(lncRNA)):
#     for j in range(len(lncRNA)):
#         CL[i][j] = (LM_M[i,:].dot(LM_M[j,:]))/(norm(LM_M[i,:])*norm(LM_M[j,:]))
# np.savetxt("CL.csv",CL,delimiter=',',fmt="%.5f")

In [26]:
CL = np.loadtxt("./CL.csv",delimiter=',',dtype=float)

In [27]:
JD = np.zeros(shape=CD.shape)
for i in range(MD_M.shape[-1]):
    for j in range(MD_M.shape[-1]):
        JD[i][j] =(np.bitwise_and(MD_M[:,i],MD_M[:,j]).sum())/(np.bitwise_or(MD_M[:,i],MD_M[:,j]).sum())
        

In [28]:
JL = np.zeros(shape=CL.shape)
for i in range(LM_M.shape[-1]):
    for j in range(LM_M.shape[-1]):
        JL[i][j] =(np.bitwise_and(LM_M[:,i],LM_M[:,j]).sum())/(np.bitwise_or(LM_M[:,i],LM_M[:,j]).sum())
JL      

array([[1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.28849315, 1.        , 0.28849315, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.28849315, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [29]:
IDS = np.zeros(shape=CD.shape)
for i in range(IDS.shape[0]):
    for j in range(IDS.shape[-1]):
        if CD[i][j] == 0:
            IDS[i][j] = JD[i][j]
        else:
            IDS[i][j] = (CD[i][j]+JD[i][j])/2
IDS

array([[1.        , 0.73534833, 0.62628227, ..., 0.        , 0.        ,
        0.        ],
       [0.73534833, 1.        , 0.79003636, ..., 0.19620955, 0.19620955,
        0.        ],
       [0.62628227, 0.79003636, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.19620955, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.19620955, 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [30]:
ILS = np.zeros(shape=CL.shape)
for i in range(ILS.shape[0]):
    for j in range(ILS.shape[-1]):
        if CL[i][j] == 0:
            ILS[i][j] = JL[i][j]
        else:
            ILS[i][j] = (CL[i][j]+JL[i][j])/2
ILS

array([[1.        , 0.50909658, 0.80073   , ..., 0.        , 0.        ,
        0.        ],
       [0.50909658, 1.        , 0.42427158, ..., 0.        , 0.        ,
        0.        ],
       [0.80073   , 0.42427158, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.5       , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.5       ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ]])

Latent Factor model

In [31]:
def latent_factor_model(ALM, AMD, k, alpha=2*10**-6, lmbda=4*10**-5, max_iter=1000):
    """
    Latent factor model for calculating lncRNA-disease associations.

    Args:
        ALM (numpy.ndarray): Adjacency matrix of lncRNA-miRNA associations (m x n).
        AMD (numpy.ndarray): Adjacency matrix of miRNA-disease associations (n x e).
        k (int): Number of latent factors.
        alpha (float): Learning rate for gradient descent.
        lmbda (float): Regularization parameter.
        max_iter (int): Maximum number of iterations for gradient descent.

    Returns:
        X (numpy.ndarray): lncRNA feature matrix (m x k).
        Y (numpy.ndarray): Disease feature matrix (e x k).
        psi (numpy.ndarray): lncRNA-disease association score matrix (m x e).
    """


    # Calculate the preliminary lncRNA-disease association matrix
    ALD = ALM @ AMD

    m = ALD.shape[0]
    e = ALD.shape[1]

    # Initialize feature matrices randomly
    X = np.random.rand(m, k)
    Y = np.random.rand(e, k)

    for _ in range(max_iter):
        # Calculate the lncRNA-disease association score matrix
        psi = X @ Y.T

        # Calculate the loss function and gradients
        loss = np.sum((psi - ALD) ** 2) + lmbda * (np.sum(norm(X)) + np.sum(norm(Y)))
        grad_X = 2 * (psi - ALD) @ Y + 2 * lmbda * X
        grad_Y = 2 * (psi - ALD).T @ X + 2 * lmbda * Y

        # Update feature matrices using gradient descent
        X -= alpha * grad_X
        Y -= alpha * grad_Y

    return X, Y, psi
X,Y,phi = latent_factor_model(LM_M,MD_M,213,max_iter=500)
X,Y,phi

(array([[ 0.6861713 ,  0.75994243,  0.21371615, ...,  0.50727344,
          0.42857192,  0.56267685],
        [ 0.5798644 ,  0.59740619,  0.57554681, ...,  0.18083498,
          0.68850931,  0.6677027 ],
        [ 0.05071246,  0.48258434,  0.94861737, ...,  0.54510704,
          0.893524  ,  0.20191439],
        ...,
        [-0.06400773,  0.44531077, -0.07160656, ...,  0.2248145 ,
          0.46105783,  0.28968008],
        [ 0.83619002, -0.08233237,  0.09042959, ...,  0.33955705,
          0.80718303,  0.13634343],
        [-0.00554788,  0.7125678 ,  0.57721294, ...,  0.06648706,
          0.51411879,  0.03596589]]),
 array([[-0.09486841, -0.04022008,  0.04187271, ..., -0.05120075,
         -0.04071445, -0.151504  ],
        [-0.22001881,  0.11500278,  0.23126758, ..., -0.17832766,
         -0.10455319, -0.03971622],
        [-0.23377193,  0.10185752,  0.12601628, ...,  0.00568922,
          0.07865241, -0.04983028],
        ...,
        [ 0.07389571,  0.02106573, -0.07346749, ..., -

In [ ]:
phi

In [32]:
ILS.shape, phi.shape,len(lncRNA)

((7554, 7554), (7554, 514), 7554)

In [33]:
LP = np.zeros(shape=LD_M.shape)
for i in range(LP.shape[0]):
    for j in range(len(lncRNA)):
        LP[i,:] += ILS[i,j]*phi[j,:] 
    LP[i,:] /= norm(ILS[i:]) 
LP

In [ ]:
DP = np.zeros(shape=LD_M.shape)
for j in range(DP.shape[1]):
    for i in range(len(disease)):
        DP[:,j] += IDS[i,j]*phi[:,i]
    DP[:,j] /= norm(IDS[:,j])
DP

array([[ 1.05931873e+02,  1.07116370e+02,  1.05603883e+02, ...,
         4.30675538e+01,  4.30675538e+01,  2.73716817e+01],
       [ 7.29134576e+01,  7.39872255e+01,  7.29492168e+01, ...,
         3.03804790e+01,  3.03804790e+01,  1.54331732e+01],
       [ 1.14460020e+02,  1.16022496e+02,  1.14286211e+02, ...,
         4.72827269e+01,  4.72827269e+01,  1.73260187e+01],
       ...,
       [-2.46556130e-01, -6.34171801e-03,  6.23640249e-02, ...,
         8.87007773e-03,  8.87007773e-03, -3.51283486e-01],
       [-2.97602147e+00, -3.09064072e+00, -3.04034347e+00, ...,
        -1.51241414e+00, -1.51241414e+00,  1.59951149e-01],
       [-2.23136637e+00, -2.28871554e+00, -2.28318239e+00, ...,
        -9.61604720e-01, -9.61604720e-01,  1.49380792e-01]])

In [ ]:
LP.shape,DP.shape,ILS.shape,IDS.shape

((7554, 514), (7554, 514), (7554, 7554), (514, 514))

In [ ]:
LFMP = np.zeros(shape=LD_M.shape)
w = 0.50
for i in range(LFMP.shape[0]):
    for j in range(LFMP.shape[1]):
        LFMP[i][j] = (w*LP[i][j] + (1-w)*DP[i][j])/(norm(ILS[i,:])+norm(IDS[:,j]))
LFMP

array([[1.62968133, 1.66571155, 1.72229932, ..., 0.89975207, 0.89973404,
        0.62841064],
       [1.29888122, 1.33442765, 1.39047752, ..., 0.77954826, 0.77940625,
        0.44547169],
       [2.03151169, 2.07940851, 2.17340644, ..., 1.23524544, 1.23505245,
        0.51072483],
       ...,
       [1.80952549, 2.16642527, 2.01305046, ..., 0.16656201, 0.17933206,
        0.1513848 ],
       [2.85268295, 3.37428052, 3.06935083, ..., 0.12851203, 0.17069962,
        0.32589176],
       [4.62845485, 5.44111612, 4.98668531, ..., 0.32431728, 0.38426294,
        0.55373479]])

In [ ]:
LFMP[lncRNA_index['NONHSAT006834.2']][disease_index['Ganglioneuroma']]

0.8682090057727859